CREATE OR REPLACE VIEW EPIC_GEO AS
SELECT 
	org_units.CODE as ORG_CODE, org_units.NAME, org_units.GEO_POINT_CODE,GEO_POINTS.NAME as GEO_NAME,COUNTRY_CODE,REPORTING_CODE,ORGANIZATION_ID
FROM org_units, GEO_POINTS
where GEO_POINT_CODE = GEO_POINTS.CODE;
